### ISSUE TITLE
router

### ISSUE THREAD

**Issue by benhalverson** [benhalverson/coinbase-chart-react#16]
- Create another view (for example an about page)
- Add react-router to switch between views

**Comment by jhorner32** [comment]
Would love to work on this if @edant92 decides to pass.

**Comment by benhalverson** [comment]
@edant92 Are you still working on this?

**Comment by edant92** [comment]
I did the work on it but was having issues with GitHub authentication so
couldn't push. I wanted to try and get it resolved but I don't think I'll
have the time, sorry :/

Someone else can take over.

**Comment by jhorner32** [comment]
I'll jump on it @edant92

**Comment by jhorner32** [comment]
Pull request created. Looking forward to your feedback :)

**Comment by benhalverson** [comment]
great work @jhorner32 👍 🎉
